import Head from "next/head";
import { uuid } from "uuidv4";
import { useState } from "react";
export default function Home() {
  const [input, setInput] = useState("");
  const [todos, setTodos] = useState([]);
  const addTodo = () => {
    if (input != "") {
      setTodos((prevTodos) => [{ label: input, key: uuid() }, ...prevTodos]);
      setInput("");
    }
  };
  const deleteTodo = (key) => {
    setTodos(todos.filter((item) => item.key != key));
  };
  const handleItemImportant = (key) => {
    setTodos((prevItems) =>
      prevItems.map((item) => {
        if (item.key === key) {
          return { ...item, important: !item.important };
        } else return item;
      })
    );
  };

  return (
    <div className="main-wrapper">
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Alisher's ToDo</h1>
      <input
        className="form-label"
        placeholder="Enter Todo"
        value={input}
        type="text"
        onChange={(event) => {
          setInput(event.target.value);
        }}
      />
      <button className="btn btn-primary" onClick={addTodo}>
        Create ToDo
      </button>
      {todos.map((item) => (
        <div key={item.key} className="todo-item">
          <span
            onClick={() => handleItemImportant(item.key)}
            className={`label ${item.important ? "important" : ""}`}
          >
            {item.label}
          </span>
          <button
            className="btn btn-danger"
            onClick={() => deleteTodo(item.key)}
          >
            Delete
          </button>
        </div>
      ))}
    </div>
  );
}
