import Head from "next/head";
import { uuid } from "uuidv4";
import { useState } from "react";
export default function Home() {
  const [input, setInput] = useState("");
  const [todos, setTodos] = useState([]);
  const addTodo = () => {
    setTodos((prevTodos) => [{ label: input, key: uuid() }, ...prevTodos]);
    setInput("");
  };
  const deleteTodo = (key) => {
    console.log(key);
  };
  return (
    <div>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <input
        value={input}
        type="text"
        onChange={(event) => {
          setInput(event.target.value);
        }}
      />
      <button onClick={addTodo}>Create ToDo</button>
      {todos.map((item) => (
        <>
          <h2>{item.label}</h2>
          <button onClick={() => deleteTodo(item.key)}>Delete</button>
        </>
      ))}
    </div>
  );
}
